CLUB_NAME_MAPPING = {
    '39': {  # Premier League
        'Arsenal': 'Arsenal',
        'Aston Villa': 'Aston Villa',
        'Bournemouth': 'Bournemouth',
        'Brentford': 'Brentford',
        'Brighton': 'Brighton',
        'Burnley': 'Burnley',
        'Chelsea': 'Chelsea',
        'Crystal Palace': 'Crystal Palace',
        'Everton': 'Everton',
        'Fulham': 'Fulham',
        'Leeds': 'Leeds',
        'Liverpool': 'Liverpool',
        'Manchester City': 'Man City',
        'Manchester United': 'Man United',
        'Newcastle': 'Newcastle',
        'Nottingham Forest': 'Forest',
        'Sunderland': 'Sunderland',
        'Tottenham': 'Tottenham',
        'West Ham': 'West Ham',
        'Wolves': 'Wolves'
    },
    '61': {  # Ligue 1
        'Angers': 'Angers',
        'Auxerre': 'Auxerre',
        'Le Havre': 'Le Havre',
        'Lens': 'Lens',
        'Lille': 'Lille',
        'Lorient': 'Lorient',
        'Lyon': 'Lyon',
        'Marseille': 'Marseille',
        'Metz': 'Metz',
        'Monaco': 'Monaco',
        'Nantes': 'Nantes',
        'Nice': 'Nice',
        'Paris FC': 'Paris FC',
        'Paris Saint Germain': 'Paris SG',
        'Rennes': 'Rennes',
        'Stade Brestois 29': 'Brest',
        'Strasbourg': 'Strasbourg',
        'Toulouse': 'Toulouse'
    },
    '78': {  # Bundesliga
        '1. FC Heidenheim': 'Heidenheim',
        '1. FC Köln': 'Koeln',
        '1899 Hoffenheim': 'Hoffenheim',
        'Bayer Leverkusen': 'Leverkusen',
        'Bayern München': 'Bayern',
        'Borussia Dortmund': 'Dortmund',
        'Borussia Mönchengladbach': 'Gladbach',
        'Eintracht Frankfurt': 'Frankfurt',
        'FC Augsburg': 'Augsburg',
        'FC St. Pauli': 'St Pauli',
        'FSV Mainz 05': 'Mainz',
        'Hamburger SV': 'Hamburg',
        'RB Leipzig': 'RB Leipzig',
        'SC Freiburg': 'Freiburg',
        'Union Berlin': 'Union Berlin',
        'VfB Stuttgart': 'Stuttgart',
        'VfL Wolfsburg': 'Wolfsburg',
        'Werder Bremen': 'Werder'
    },
    '140': {  # La Liga
        'Alaves': 'Alaves',
        'Athletic Club': 'Bilbao',
        'Atletico Madrid': 'Atletico',
        'Barcelona': 'Barcelona',
        'Celta Vigo': 'Celta',
        'Elche': 'Elche',
        'Espanyol': 'Espanyol',
        'Getafe': 'Getafe',
        'Girona': 'Girona',
        'Levante': 'Levante',
        'Mallorca': 'Mallorca',
        'Osasuna': 'Osasuna',
        'Oviedo': 'Oviedo',
        'Rayo Vallecano': 'Rayo Vallecano',
        'Real Betis': 'Betis',
        'Real Madrid': 'Real Madrid',
        'Real Sociedad': 'Sociedad',
        'Sevilla': 'Sevilla',
        'Valencia': 'Valencia',
        'Villarreal': 'Villarreal'
    },
    '135': {  # Serie A
        'AC Milan': 'Milan',
        'AS Roma': 'Roma',
        'Atalanta': 'Atalanta',
        'Bologna': 'Bologna',
        'Cagliari': 'Cagliari',
        'Como': 'Como',
        'Cremonese': 'Cremonese',
        'Fiorentina': 'Fiorentina',
        'Genoa': 'Genoa',
        'Inter': 'Inter',
        'Juventus': 'Juventus',
        'Lazio': 'Lazio',
        'Lecce': 'Lecce',
        'Napoli': 'Napoli',
        'Parma': 'Parma',
        'Pisa': 'Pisa',
        'Sassuolo': 'Sassuolo',
        'Torino': 'Torino',
        'Udinese': 'Udinese',
        'Verona': 'Verona'
    },
    '94': {  # Liga Portugal
        'AVS': 'AVS Futebol',
        'Alverca': 'Alverca',
        'Arouca': 'Arouca',
        'Benfica': 'Benfica',
        'Casa Pia': 'Casa Pia',
        'Estoril': 'Estoril',
        'Estrela': 'Estrela Amadora',
        'FC Porto': 'Porto',
        'Famalicao': 'Famalicao',
        'GIL Vicente': 'Gil Vicente',
        'Guimaraes': 'Guimaraes',
        'Moreirense': 'Moreirense',
        'Nacional': 'Nacional',
        'Rio Ave': 'Rio Ave',
        'SC Braga': 'Braga',
        'Santa Clara': 'Santa Clara',
        'Sporting CP': 'Sporting',
        'Tondela': 'Tondela'
    },
    '88': {  # Eredivisie
        'AZ Alkmaar': 'Alkmaar',
        'Ajax': 'Ajax',
        'Excelsior': 'Excelsior',
        'FC Volendam': 'Volendam',
        'Feyenoord': 'Feyenoord',
        'Fortuna Sittard': 'Sittard',
        'GO Ahead Eagles': 'Go Ahead Eagles',
        'Groningen': 'Groningen',
        'Heerenveen': 'Heerenveen',
        'Heracles': 'Heracles',
        'NAC Breda': 'Breda',
        'NEC Nijmegen': 'Nijmegen',
        'PEC Zwolle': 'Zwolle',
        'PSV Eindhoven': 'PSV',
        'Sparta Rotterdam': 'Sparta Rotterdam',
        'Telstar': 'Telstar',
        'Twente': 'Twente',
        'Utrecht': 'Utrecht'
    },
    '197': {  # Super League (GRE)
        'AEK Athens FC': 'AEK',
        'Aris Thessalonikis': 'Aris',
        'Asteras Tripolis': 'Asteras Tripolis',
        'Atromitos': 'Atromitos',
        'Kifisia': 'Kifisias',
        'Larisa': 'Larisa',
        'Levadiakos': 'Levadeiakos',
        'OFI': 'OFI',
        'Olympiakos Piraeus': 'Olympiakos',
        'PAOK': 'PAOK',
        'Panathinaikos': 'Panathinaikos',
        'Panetolikos': 'Panetolikos',
        'Panserraikos': 'Panserraikos',
        'Volos NFC': 'NFC Volos'
    },
    '203': {  # Süper Lig
        'Alanyaspor': 'Alanyaspor',
        'Antalyaspor': 'Antalyaspor',
        'Başakşehir': 'Bueyueksehir',
        'Beşiktaş': 'Besiktas',
        'Eyüpspor': 'Eyupspor',
        'Fatih Karagümrük': 'Fatih Karaguemruek',
        'Fenerbahçe': 'Fenerbahce',
        'Galatasaray': 'Galatasaray',
        'Gazişehir Gaziantep': 'Gaziantep FK',
        'Genclerbirligi': 'Genclerbirligi',
        'Göztepe': 'Goeztepe',
        'Kasımpaşa': 'Kasimpasa',
        'Kayserispor': 'Kayseri',
        'Kocaelispor': 'Kocaelispor',
        'Konyaspor': 'Konyaspor',
        'Rizespor': 'Rizespor',
        'Samsunspor': 'Samsunspor',
        'Trabzonspor': 'Trabzonspor'
    }
}